### ISSUE TITLE
A little confusions in tests

### ISSUE THREAD

**Issue by RubenAshughyan** [ando-khachatryan/Kalah#1]
Dear @ando-khachatryan I had some confusions about the tests. Can you please look at them. 
Thanks
1) test_make_move_9
```
before:
   [ 4  2 13  3  0  1]   
0                        0
   [1 2 3 4 5 6]   

after:
   [5 3 0 4 1 2]   
1                  1
   [2 3 4 5 6 7]   
```
So shouldn't it be 
`should_be = KalahGame([2, 3, 4, 5, 6, 7], [2, 1, 4, 0, 3, 5], Side.SOUTH, 1, 1)`?
instead of:
`should_be = KalahGame([2, 3, 0, 5, 6, 7], [2, 1, 4, 0, 3, 5], Side.SOUTH, 0, 6)`

2) testGameEndCondition1
```
before:
   [1 0 0 0 0 0]   
0                  0
   [1 2 1 3 1 4]   


after:
   [0 0 0 0 0 0]   
1                  0
   [1 2 1 3 1 4]   
```
Shouldn't it be
`self.assertEqual(finished, False)`
`self.assertEqual(res, -2)`
?
3) testGameEndCondition2
```
before:
   [ 4  2 13  3  0  1]   
35                       0
   [1 2 3 4 5 6]   
Turn: North #Stones : 79 

after:
   [5 3 0 4 1 2]   
36                 1
   [2 3 4 5 6 7]   
Turn: North #Stones : 79 
```
`2*36 < 79` so shouldn't it be
`self.assertEqual(finished, False)`?
`self.assertEqual(res, -2)`?
since the game is not finished

**Comment by ando-khachatryan** [comment]
Ruben, have a look at the rules of the game.
1. You don't put a stone in your opponents Kalah.
2. If one of the players has no stones in all their pits, the game is over -- the opponent removes all their stones, puts on his Kalah, and then you count the stones in Kalahs.

**Comment by RubenAshughyan** [comment]
Thanks @ando-khachatryan , sorry for inconvenience.
